[build]
command = "npm run start"  # The command to start your server locally
targetPort = 5000          # The port your app runs on locally
functions = "netlify/functions" # Directory for serverless functions

[dev]
framework = "#custom"
port = 8888                # Port for Netlify Dev server
