[build]
command = "npm run start"  # Replace with your actual start command
targetPort = 5000          # Port your backend runs on locally

[dev]
framework = "#custom"      # Indicate a custom framework
command = "npm run start"  # Start command for local development
targetPort = 5000          # Local server port for your backend
port = 8888                # Proxy server port for Netlify Dev
